Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: igors-sfcb-ctf-bucket-us-west-2
      VersioningConfiguration:
        Status: Suspended